#!/usr/bin/env python3
"""Audit Positronic session/recording identity changes after v0.2.1."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path
from typing import Any


FAMILY = Path(__file__).resolve().parent
ROOT = FAMILY.parent.parent
DEFAULT_REPOSITORY = ROOT / "work" / "h196-positronic-history"
PROTOCOL = FAMILY / "protocol-h196-positronic-session-identity-history.md"
INCIDENT = FAMILY / "incident-h196-expansion-history-exposure.md"
H195_RESULT = FAMILY / "result-h195-phail-session-identity-recording-trace.json"
OUTPUT = FAMILY / "result-h196-positronic-session-identity-history.json"

REMOTE = "https://github.com/Positronic-Robotics/positronic"
BASE = "e406176bc526babb06844a48e3627a5c0409eb74"
HEAD = "01b78e6f62ff5913490c360afdd2712eee070524"
RESOLVED_AT = "2026-07-28T09:57:28Z"
H195_RESULT_SHA256 = "140b9720efd8490869be403734ad0edb218f8c9ed4d006ebae69e3aff52055ab"

FIXED_PATHS = (
    "positronic/policy/remote.py",
    "positronic/offboard/client.py",
    "positronic/offboard/vendor_server.py",
    "positronic/data_collection.py",
    "positronic/dataset/episode.py",
    "positronic/dataset/ds_writer_agent.py",
    "positronic/policy/harness.py",
    "positronic/inference.py",
    "positronic/wire.py",
    "positronic/dataset/local_dataset.py",
    "positronic/cfg/policy.py",
    "positronic/policy/base.py",
    "positronic/policy/codec.py",
    "positronic/vendors/lerobot_0_3_3/server.py",
    "positronic/vendors/lerobot/server.py",
    "positronic/vendors/gr00t/server.py",
    "positronic/vendors/openpi/server.py",
)
EXPANSION_PATHS = (
    "positronic/policy/recording.py",
    "positronic/offboard/server.py",
)
PATHS = FIXED_PATHS + EXPANSION_PATHS

VOCABULARY = (
    "session_id",
    "session uuid",
    "session_uuid",
    "inference_session_id",
    "inference session",
    "request_id",
    "request uuid",
    "request_uuid",
    "execution_id",
    "trace_id",
    "run_id",
    "episode_uuid",
    "uuid",
    "ulid",
    "recording",
    "recording_dir",
    "RecordingCodec",
    ".rrd",
    "ready",
    "meta",
    "static",
    "reset",
    "writer",
)

ALLOWED_CLASSIFICATIONS = {
    "collision_resistant_identifier_recorded",
    "recording_locator_recorded_without_collision_resistant_identifier",
    "locator_still_unjoined",
    "no_relevant_implementation_change",
    "architecture_changed_trace_incomplete",
}

BACKENDS = {
    "ACT": "positronic/vendors/lerobot_0_3_3/server.py",
    "SmolVLA": "positronic/vendors/lerobot/server.py",
    "GR00T": "positronic/vendors/gr00t/server.py",
    "OpenPI": "positronic/vendors/openpi/server.py",
}

EXPANSIONS = [
    {
        "origin_path": "positronic/policy/remote.py",
        "origin_symbol": "Recorder",
        "target_path": "positronic/policy/recording.py",
        "target_symbol": "Recorder",
        "reason": "resolve current recording-locator creation and session metadata exposure",
        "history_status": "result_exposed",
    },
    {
        "origin_path": "positronic/vendors/lerobot_0_3_3/server.py; "
        "positronic/vendors/lerobot/server.py; "
        "positronic/vendors/gr00t/server.py; "
        "positronic/vendors/openpi/server.py",
        "origin_symbol": "serve",
        "target_path": "positronic/offboard/server.py",
        "target_symbol": "serve / PolicyServer",
        "reason": "resolve replacement server ready-metadata and recording-wrapper path",
        "history_status": "result_exposed",
    },
]

LIMITATIONS = [
    "The endpoint result is bounded to public Positronic commit "
    "01b78e6f62ff5913490c360afdd2712eee070524; main may later change.",
    "The two expansion-path introduction timings are result-exposed and exploratory; "
    "the comparison-endpoint semantic trace was prospectively authorized.",
    "Current public code does not establish the exact code deployed for the historical "
    "PhAIL evaluation or retroactively add fields to its released episodes.",
    "The episode uid is generated by the dataset writer and is not embedded in or "
    "transmitted back to the server recording; the recorded RRD path supplies the join.",
    "The RRD filename still combines second-resolution wall time with a process-wide "
    "counter, so uniqueness across process restarts is not established.",
    "A finalized inference episode is not automatically a physical reset, operator "
    "session, exchangeability cluster, or independence unit.",
    "No configured recording location or private service was accessed, so recording "
    "availability and retention remain unknown.",
]

INTERPRETATION = (
    "At pinned public main, all four public PhAIL server commands still configure a "
    "recording directory. The redesigned server creates a per-websocket-session RRD "
    "recording; its session metadata now exposes the full path as recording.rrd, the "
    "ready handshake carries it to the remote session, and the harness writes it to "
    "the finalized episode's static.json as inference.policy.server.recording.rrd. "
    "Independently, each normally created stored episode receives a uuid4 uid in "
    "meta.json. Thus current public code implements both a collision-resistant "
    "episode identifier and an explicit episode-to-server-recording locator join, "
    "without establishing reset quality or a valid dependence cluster."
)


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def git(repo: Path, *args: str, text: bool = True) -> str | bytes:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=text,
    )
    return proc.stdout


def commit_meta(repo: Path, commit: str) -> dict[str, Any]:
    raw = str(git(repo, "show", "-s", "--format=%H%x00%aI%x00%cI%x00%P%x00%s", commit))
    sha, author_date, commit_date, parents, subject = raw.rstrip("\n").split("\x00")
    return {
        "commit": sha,
        "author_date": author_date,
        "commit_date": commit_date,
        "parents": parents.split() if parents else [],
        "parent_count": len(parents.split()) if parents else 0,
        "subject": subject,
    }


def blob_record(repo: Path, commit: str, path: str) -> dict[str, Any]:
    exists = subprocess.run(
        ["git", "-C", str(repo), "cat-file", "-e", f"{commit}:{path}"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    ).returncode == 0
    if not exists:
        return {"present": False}
    data = bytes(git(repo, "show", f"{commit}:{path}", text=False))
    blob = str(git(repo, "rev-parse", f"{commit}:{path}")).strip()
    return {
        "present": True,
        "git_blob": blob,
        "sha256": sha256_bytes(data),
        "line_count": data.count(b"\n") + (0 if data.endswith(b"\n") or not data else 1),
    }


def parse_name_status(raw: str) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    for line in raw.splitlines():
        if not line:
            continue
        fields = line.split("\t")
        status = fields[0]
        if status.startswith(("R", "C")):
            require(len(fields) == 3, f"bad rename/copy status: {line}")
            records.append({"status": status, "old_path": fields[1], "path": fields[2]})
        else:
            require(len(fields) == 2, f"bad name status: {line}")
            records.append({"status": status, "path": fields[1]})
    return records


def tracked_paths_with_renames(repo: Path) -> tuple[str, ...]:
    tracked = set(PATHS)
    while True:
        commits = str(
            git(repo, "log", "--reverse", "--format=%H", f"{BASE}..{HEAD}", "--", *sorted(tracked))
        ).splitlines()
        added: set[str] = set()
        for commit in commits:
            meta = commit_meta(repo, commit)
            if not meta["parents"]:
                continue
            raw = str(
                git(
                    repo,
                    "diff-tree",
                    "--no-commit-id",
                    "-r",
                    "-M",
                    "--name-status",
                    meta["parents"][0],
                    commit,
                )
            )
            for record in parse_name_status(raw):
                if record["status"].startswith("R") and record["old_path"] in tracked:
                    added.add(record["path"])
        if not (added - tracked):
            return tuple(sorted(tracked))
        tracked |= added


def vocabulary_matches(text: str) -> list[str]:
    lower = text.lower()
    return [term for term in VOCABULARY if term.lower() in lower]


def history(repo: Path, tracked: tuple[str, ...]) -> list[dict[str, Any]]:
    commits = str(
        git(repo, "log", "--reverse", "--format=%H", f"{BASE}..{HEAD}", "--", *tracked)
    ).splitlines()
    out: list[dict[str, Any]] = []
    for commit in commits:
        meta = commit_meta(repo, commit)
        require(meta["parents"], f"unexpected root commit in range: {commit}")
        parent = meta["parents"][0]
        raw_status = str(
            git(
                repo,
                "diff-tree",
                "--no-commit-id",
                "-r",
                "-M",
                "--name-status",
                parent,
                commit,
                "--",
                *tracked,
            )
        )
        changes = parse_name_status(raw_status)
        require(changes, f"path-selected commit has no retained changes: {commit}")
        patch = str(git(repo, "diff", "--find-renames", parent, commit, "--", *tracked))
        meta["changes"] = changes
        meta["subject_vocabulary_matches"] = vocabulary_matches(meta["subject"])
        meta["patch_vocabulary_matches"] = vocabulary_matches(patch)
        meta["patch_sha256"] = sha256_bytes(patch.encode("utf-8"))
        out.append(meta)
    require(len({item["commit"] for item in out}) == len(out), "duplicate history commit")
    return out


def source(repo: Path, path: str) -> str:
    return str(git(repo, "show", f"{HEAD}:{path}"))


def require_fragments(text: str, path: str, fragments: tuple[str, ...]) -> None:
    for fragment in fragments:
        require(fragment in text, f"{path}: required fragment missing: {fragment}")


def semantic_trace(repo: Path) -> dict[str, Any]:
    recording = source(repo, "positronic/policy/recording.py")
    server = source(repo, "positronic/offboard/server.py")
    client = source(repo, "positronic/offboard/client.py")
    remote = source(repo, "positronic/policy/remote.py")
    base = source(repo, "positronic/policy/base.py")
    harness = source(repo, "positronic/policy/harness.py")
    writer_agent = source(repo, "positronic/dataset/ds_writer_agent.py")
    local_dataset = source(repo, "positronic/dataset/local_dataset.py")
    cfg_policy = source(repo, "positronic/cfg/policy.py")

    require_fragments(
        recording,
        "positronic/policy/recording.py",
        (
            "_EPISODE_COUNTER = itertools.count(1)",
            "self._rrd_path = self._dir / f'{ts}_{episode_num:04d}.rrd'",
            "return {**self._inner.meta, 'recording.rrd': str(self._rec._rrd_path)}",
        ),
    )
    require_fragments(
        server,
        "positronic/offboard/server.py",
        (
            "rec = Recorder(self._recording_dir)",
            "session = await asyncio.to_thread(served.new_session)",
            "**session.meta",
            "await websocket.send_bytes(serialise({'status': 'ready', 'meta': meta}))",
        ),
    )
    require_fragments(
        client,
        "positronic/offboard/client.py",
        (
            "self._metadata = self._handshake()",
            "if status == 'ready':",
            "return response['meta']",
            "def metadata(self) -> dict[str, Any]:",
        ),
    )
    require_fragments(
        remote,
        "positronic/policy/remote.py",
        (
            "return flatten_dict({'type': 'remote', 'server': self._session.metadata})",
            "ws_session = self._client.new_session()",
        ),
    )
    require_fragments(
        base,
        "positronic/policy/base.py",
        (
            "return {**self._policy_meta, **self._inner.meta, self._key_field: self._key}",
            "return _KeyedSession(session, policy.meta, self._key_field, key)",
        ),
    )
    require_fragments(
        harness,
        "positronic/policy/harness.py",
        (
            "session_meta = self.policy.meta | (self._session.meta if self._session else {})",
            "meta[f'inference.policy.{k}'] = v",
            "self._session = self.policy.new_session(self.context, clock.now)",
            "self.ds_command.emit(DsWriterCommand.START())",
            "self.ds_command.emit(DsWriterCommand.STOP({**self._build_episode_meta(self.context), **(payload or {})}))",
        ),
    )
    require_fragments(
        writer_agent,
        "positronic/dataset/ds_writer_agent.py",
        (
            "ep_writer = self.ds_writer.new_episode()",
            "for k, v in cmd.static_data.items():",
            "ep_writer.set_static(k, v)",
            "ep_writer.__exit__(None, None, None)",
        ),
    )
    require_fragments(
        local_dataset,
        "positronic/dataset/local_dataset.py",
        (
            "'uid': uid or uuid.uuid4().hex",
            "with (self._path / 'meta.json').open('w', encoding='utf-8') as f:",
            "json.dump(self._meta, f, indent=2)",
            "episode_json = self._path / 'static.json'",
            "json.dump(self._static_items, f, indent=2, cls=_StaticEncoder)",
        ),
    )
    require_fragments(
        cfg_policy,
        "positronic/cfg/policy.py",
        (
            "phail_multiple = production.override(",
            "endpoints={'smolvla': 'notebook:8000', 'act': 'notebook:8001', "
            "'groot': 'desktop:8000', 'openpi': 'vm-openpi:8000'}",
        ),
    )

    backend_records = []
    for policy, path in BACKENDS.items():
        text = source(repo, path)
        require("'phail': serve.override(" in text, f"{path}: PhAIL command missing")
        match = re.search(
            r"'phail':\s*serve\.override\((?P<body>.*?)\n\s*\),",
            text,
            flags=re.DOTALL,
        )
        require(match is not None, f"{path}: cannot bound PhAIL override")
        body = match.group("body")
        rec_match = re.search(r"recording_dir\s*=\s*'([^']+)'", body)
        require(rec_match is not None, f"{path}: PhAIL recording directory missing")
        backend_records.append(
            {
                "policy": policy,
                "source_path": path,
                "phail_recording_directory": rec_match.group(1),
                "recording_enabled": True,
            }
        )

    # The final flattened static key follows directly from:
    # recording.rrd -> server.recording.rrd -> inference.policy.<key>.
    final_rrd_key = "inference.policy.server.recording.rrd"
    return {
        "fixed_phail_backend_results": backend_records,
        "server_recorder_constructed_per_websocket_session": True,
        "server_recording_locator_pattern": "{YYMMDD_HHMMSS}_{process_wide_counter:04d}.rrd",
        "server_recording_locator_uniqueness": (
            "process-wide counter plus second-resolution wall time; cross-restart uniqueness not established"
        ),
        "server_recording_locator_exposed_in_session_meta": True,
        "ready_handshake_transports_session_meta": True,
        "client_preserves_ready_metadata": True,
        "remote_session_nests_server_metadata": True,
        "sampled_policy_preserves_selected_session_meta": True,
        "harness_creates_one_policy_session_and_one_writer_episode_per_run": True,
        "harness_finalizes_session_meta_into_writer_static_data": True,
        "final_static_rrd_key": final_rrd_key,
        "final_static_rrd_key_derivation": [
            "recording.rrd",
            "server.recording.rrd",
            final_rrd_key,
        ],
        "static_data_serialized_to_static_json": True,
        "normal_writer_path_calls_new_episode_without_uid_override": True,
        "episode_uid_construction": "uuid.uuid4().hex",
        "episode_uid_persisted_key": "uid",
        "episode_uid_serialized_to_meta_json": True,
        "episode_uid_embedded_in_server_recording": False,
        "recording_locator_supplies_episode_to_rrd_join": True,
        "physical_reset_or_operator_session_established": False,
    }


def build(repo: Path) -> dict[str, Any]:
    require(repo.is_dir(), f"repository missing: {repo}")
    require(str(git(repo, "rev-parse", BASE)).strip() == BASE, "baseline commit mismatch")
    require(str(git(repo, "rev-parse", HEAD)).strip() == HEAD, "comparison commit mismatch")
    subprocess.run(
        ["git", "-C", str(repo), "merge-base", "--is-ancestor", BASE, HEAD],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    require(not str(git(repo, "status", "--porcelain=v1")).strip(), "source checkout is dirty")
    require(sha256_file(H195_RESULT) == H195_RESULT_SHA256, "H195 dependency hash mismatch")
    require(PROTOCOL.is_file() and INCIDENT.is_file(), "H196 protocol or incident missing")

    tracked = tracked_paths_with_renames(repo)
    hist = history(repo, tracked)
    trace = semantic_trace(repo)
    classification = "collision_resistant_identifier_recorded"
    require(classification in ALLOWED_CLASSIFICATIONS, "unsupported classification")
    require(trace["episode_uid_serialized_to_meta_json"], "classification lacks recorded UUID")
    require(trace["recording_locator_supplies_episode_to_rrd_join"], "classification lacks locator join")

    records = [
        {
            "path": path,
            "baseline": blob_record(repo, BASE, path),
            "comparison": blob_record(repo, HEAD, path),
        }
        for path in tracked
    ]
    require(
        next(r for r in records if r["path"] == "positronic/offboard/vendor_server.py")["comparison"]["present"]
        is False,
        "expected vendor_server deletion missing",
    )
    require(
        all(
            next(r for r in records if r["path"] == path)["comparison"]["present"]
            for path in EXPANSION_PATHS
        ),
        "required expansion missing at comparison endpoint",
    )

    return {
        "schema": "h196-positronic-session-identity-history-v1",
        "classification": classification,
        "interpretation": INTERPRETATION,
        "scope": (
            "Public Positronic v0.2.1-to-pinned-main source history and current "
            "PhAIL runtime-to-finalized-episode metadata path only"
        ),
        "limitations": LIMITATIONS,
        "dataset_content_opened": False,
        "performance_field_opened": False,
        "server_recording_opened": False,
        "private_service_accessed": False,
        "comparison_endpoint_prospective": True,
        "expansion_history_result_exposed": True,
        "protocol_sha256": sha256_file(PROTOCOL),
        "incident_sha256": sha256_file(INCIDENT),
        "h195_dependency_sha256": H195_RESULT_SHA256,
        "upstream": {
            "remote": REMOTE,
            "resolved_at": RESOLVED_AT,
            "baseline": commit_meta(repo, BASE),
            "comparison": commit_meta(repo, HEAD),
            "baseline_is_ancestor": True,
            "git_version": str(git(repo, "--version")).strip(),
        },
        "fixed_paths": list(FIXED_PATHS),
        "expansion_paths": list(EXPANSION_PATHS),
        "tracked_paths_after_rename_detection": list(tracked),
        "expansions": EXPANSIONS,
        "source_records": records,
        "history": {
            "status": "result_exposed_for_expansion_paths",
            "commit_count": len(hist),
            "commits": hist,
        },
        "trace": trace,
        "decision_consequence": (
            "Retain H195 as the historical v0.2.1 finding, but narrow P2's repair "
            "request: pinned current public code already records a UUID episode identity "
            "and the configured server-recording locator. The remaining request is to "
            "retain these fields in released evaluation artifacts and separately record "
            "physical reset/carryover and operator-session identity."
        ),
    }


def validate(result: dict[str, Any]) -> None:
    require(result.get("schema") == "h196-positronic-session-identity-history-v1", "schema mismatch")
    require(result.get("classification") in ALLOWED_CLASSIFICATIONS, "classification mismatch")
    require(result.get("comparison_endpoint_prospective") is True, "endpoint status mismatch")
    require(result.get("expansion_history_result_exposed") is True, "history exposure missing")
    for key in (
        "dataset_content_opened",
        "performance_field_opened",
        "server_recording_opened",
        "private_service_accessed",
    ):
        require(result.get(key) is False, f"prohibited access flag set: {key}")
    require(result.get("h195_dependency_sha256") == H195_RESULT_SHA256, "H195 dependency mismatch")
    require(result.get("fixed_paths") == list(FIXED_PATHS), "fixed path roster mismatch")
    require(result.get("expansion_paths") == list(EXPANSION_PATHS), "expansion roster mismatch")
    require(result.get("expansions") == EXPANSIONS, "expansion trace mismatch")
    commits = result.get("history", {}).get("commits")
    require(isinstance(commits, list) and commits, "history missing")
    require(result["history"].get("commit_count") == len(commits), "history count mismatch")
    require(len({item["commit"] for item in commits}) == len(commits), "duplicate history commit")
    trace = result.get("trace", {})
    require(trace.get("episode_uid_construction") == "uuid.uuid4().hex", "UUID construction mismatch")
    require(trace.get("episode_uid_serialized_to_meta_json") is True, "UUID persistence mismatch")
    require(
        trace.get("final_static_rrd_key") == "inference.policy.server.recording.rrd",
        "RRD static key mismatch",
    )
    require(trace.get("recording_locator_supplies_episode_to_rrd_join") is True, "RRD join mismatch")
    require(trace.get("physical_reset_or_operator_session_established") is False, "scope overreach")
    if result["classification"] == "collision_resistant_identifier_recorded":
        require(trace.get("episode_uid_serialized_to_meta_json") is True, "positive lacks UUID")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository", type=Path, default=DEFAULT_REPOSITORY)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    candidate = build(args.repository)
    validate(candidate)
    rendered = json.dumps(candidate, indent=2, sort_keys=True) + "\n"
    if args.check:
        require(args.output.is_file(), f"stored result missing: {args.output}")
        require(args.output.read_text(encoding="utf-8") == rendered, "stored result differs from exact rebuild")
        print(f"PASS H196 exact check: {args.output}")
    else:
        args.output.write_text(rendered, encoding="utf-8")
        print(f"WROTE {args.output}")
        print(f"classification={candidate['classification']}")
        print(f"history_commits={candidate['history']['commit_count']}")


if __name__ == "__main__":
    main()
